package open.threading.util;

/**
 * Exception generated by paranoid collections when there is concurrent access
 *
 * @author ups
 */
public class ConcurrentAccessException extends RuntimeException {

    private static final long serialVersionUID = -6818988072517691256L;

    @SuppressWarnings("WeakerAccess")
    public ConcurrentAccessException(String name) {
        super("Concurrent access triggered by method '" + name + "'");
    }

}
